services:
  - type: web
    name: bharatstack
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DB_NAME
        value: bharatstack
      - key: DEBUG
        value: "False"
      - key: UPI_ID
        sync: false
      - key: UPI_NAME
        value: BharatStack
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_FROM
        sync: false
      - key: BASE_URL
        sync: false
